name: waitingproj
description: Marraige finder

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_tts: ^1.2.6
  equatable: ^1.1.1
  data_connection_checker: ^0.3.4
  dartz: ^0.9.1
  validators: ^2.0.0
  provider: ^4.0.0
  shared_preferences: any
  build_runner: ^1.7.2
  font_awesome_flutter: '>= 4.7.0'
  simple_animations: ^2.2.1
  http: ^0.12.1
  bloc: ^4.0.0
  get_it: ^4.0.2
  flutter_bloc: ^4.0.0
  auto_route: ^0.6.9
  url_launcher: ^5.4.7
  contacts_service: ^0.4.6
  retry: ^3.0.1
  device_info: ^0.4.2+7
  clipboard: ^0.1.2+8
  ios_network_info: ^0.1.2
  connectivity: '>=0.4.9+2 <2.0.0'
  get_ip: ^0.4.0
  mockito: any 
  cached_network_image: ^2.3.2+1
  shimmer: ^1.1.1
  image_picker: ^0.6.7+7
  permission_handler: ^5.0.1+1
  share: '>=0.6.5+2 <2.0.0'
  tcard: ^1.3.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
